-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGDjCA3Pap7cJaolm
bjXJltBYB7PJUga1t+lbWdWgtiSgCgYIKoZIzj0DAQehRANCAAS4ocUNtwmtyn/q
Ur0nhL7f0jScp+VWfnnT08Or62obWiAS/jkEe4rBvKmhyML2S2TXA/zE5ez6sW8s
IRedCBBn
-----END PRIVATE KEY-----